"""add columns for soft delete

Revision ID: 0f1eba1971bf
Revises: 3729b2a94025
Create Date: 2026-02-08 15:14:10.932722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1eba1971bf'
down_revision: Union[str, Sequence[str], None] = '3729b2a94025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('delete_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_groups_delete_at'), 'groups', ['delete_at'], unique=False)
    op.add_column('posts', sa.Column('delete_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_delete_at'), 'posts', ['delete_at'], unique=False)
    op.drop_column('tokens', 'expires_at')
    op.add_column('users', sa.Column('online', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('delete_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_delete_at'), 'users', ['delete_at'], unique=False)
    op.create_index(op.f('ix_users_online'), 'users', ['online'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_online'), table_name='users')
    op.drop_index(op.f('ix_users_delete_at'), table_name='users')
    op.drop_column('users', 'delete_at')
    op.drop_column('users', 'create_at')
    op.drop_column('users', 'online')
    op.add_column('tokens', sa.Column('expires_at', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_posts_delete_at'), table_name='posts')
    op.drop_column('posts', 'delete_at')
    op.drop_index(op.f('ix_groups_delete_at'), table_name='groups')
    op.drop_column('groups', 'delete_at')
    # ### end Alembic commands ###
